language: ruby
rvm: 2.4.1
before_install:
- sudo apt-get -y --reinstall install imagemagick
script:
- if [ $TRAVIS_EVENT_TYPE = cron ]; then mkdir -p project ; fi
- if [ $TRAVIS_EVENT_TYPE = cron ]; then pushd project ; fi
- if [ $TRAVIS_EVENT_TYPE = cron ]; then echo -e "machine github.com\n  login $CI_USER_TOKEN" >> ~/.netrc ; fi
- if [ $TRAVIS_EVENT_TYPE = cron ]; then git clone --branch develop --depth 1 https://github.com/tanjoin/tanjoin.github.io.git ; fi
- if [ $TRAVIS_EVENT_TYPE = cron ]; then pushd tanjoin.github.io ; fi
- if [ $TRAVIS_EVENT_TYPE = cron ]; then git config user.name "tanjoin" ; fi
- if [ $TRAVIS_EVENT_TYPE = cron ]; then git config user.email "tanjoin@users.noreply.github.com" ; fi
- if [ $TRAVIS_EVENT_TYPE = cron ]; then echo `date` > .updated ; fi
- if [ $TRAVIS_EVENT_TYPE = cron ]; then git add .updated ; fi
- if [ $TRAVIS_EVENT_TYPE = cron ]; then git commit -m "Update .updated" ; fi
- if [ $TRAVIS_EVENT_TYPE = cron ]; then git push origin develop ; fi
- if [ $TRAVIS_EVENT_TYPE = cron ]; then popd ; fi
- if [ $TRAVIS_EVENT_TYPE = cron ]; then popd ; fi
- if [ ! $TRAVIS_EVENT_TYPE = cron ]; then mkdir -p tmp ; fi
- if [ ! $TRAVIS_EVENT_TYPE = cron ]; then pushd tmp ; fi
- if [ ! $TRAVIS_EVENT_TYPE = cron ]; then echo -e "machine github.com\n  login $CI_USER_TOKEN" >> ~/.netrc ; fi
- if [ ! $TRAVIS_EVENT_TYPE = cron ]; then git clone --branch master --depth 1 https://github.com/tanjoin/tanjoin.github.io.git ; fi
- if [ ! $TRAVIS_EVENT_TYPE = cron ]; then pushd tanjoin.github.io ; fi
- if [ ! $TRAVIS_EVENT_TYPE = cron ]; then git config user.name "tanjoin" ; fi
- if [ ! $TRAVIS_EVENT_TYPE = cron ]; then git config user.email "tanjoin@users.noreply.github.com" ; fi
- if [ ! $TRAVIS_EVENT_TYPE = cron ]; then popd ; fi
- if [ ! $TRAVIS_EVENT_TYPE = cron ]; then popd ; fi
- if [ ! $TRAVIS_EVENT_TYPE = cron ]; then bundle install --path vendor/bundle ; fi
- if [ ! $TRAVIS_EVENT_TYPE = cron ]; then JEKYLL_ENV=production bundle exec jekyll build --destination tmp/tanjoin.github.io/  ; fi
- if [ ! $TRAVIS_EVENT_TYPE = cron ]; then pushd tmp ; fi
- if [ ! $TRAVIS_EVENT_TYPE = cron ]; then pushd tanjoin.github.io ; fi
- if [ ! $TRAVIS_EVENT_TYPE = cron ]; then git add --all ; fi
- if [ ! $TRAVIS_EVENT_TYPE = cron ]; then git commit -a -m "Update _site by Travis" ; fi
- if [ ! $TRAVIS_EVENT_TYPE = cron ]; then git push origin master ; fi
- if [ ! $TRAVIS_EVENT_TYPE = cron ]; then popd ; fi
- if [ ! $TRAVIS_EVENT_TYPE = cron ]; then popd ; fi
install: true
branches:
  only:
  - develop

