# coding: utf-8

Encoding.default_external = 'UTF-8'

namespace :wiki do

  desc "wiki のリンク一覧を生成"
  task :index do
    cd '../' do
      Rake::Task['wiki:reset'].execute(Rake::TaskArguments.new([:filename], ['index.html']))
      Dir.glob("*.html").each { |html|
        if html != "index.html" && html != "template.html" then
          args = { :filename => "index.html", :text => "<a style=\"margin:5px;\" class=\"waves-effect waves-light btn light-blue darken-1 white-text text-darken-1\" href=\"#{File.basename(html)}\">#{File.basename(html, ".html")}</a>" }
          Rake::Task['wiki:putButton'].execute(Rake::TaskArguments.new(args.keys, args.values))
        end
      }
    end
  end

  desc "index.html のボタンリストを消す"
  task :reset, ["filename"] do |task, args|
    open(args.filename, "r+") { |f|
      f.flock(File::LOCK_EX)
      body = f.read
      body = body.gsub(/<div id="tanjoin-wiki">(.*)<\/div>/) do |tmp|
        "<div id=\"tanjoin-wiki\"><p><!-- wiki button bottom --></p></div>"
      end
      f.rewind
      f.puts body
      f.truncate(f.tell)
    }
  end

  desc "ボタンを追加する"
  task :putButton, ["filename", "text"] do |task, args|
    open(args.filename, "r+") { |f|
      f.flock(File::LOCK_EX)
      body = f.read
      body = body.gsub(/<!-- wiki button bottom -->/) do |tmp|
        "#{args.text}<!-- wiki button bottom -->"
      end
      f.rewind
      f.puts body
      f.truncate(f.tell)
    }
  end

end
