name: Build GitHub Pages
on:
  push:
    branches:
      - develop
jobs:
  build-develop-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - name: Checkout master branch
        uses: actions/checkout@v6
        with:
          ref: master
          path: master
          fetch-depth: 0
      - name: Build Jekyll
        run: |
          sudo apt-get -y --reinstall install imagemagick
          bundle install
          JEKYLL_ENV=production bundle exec jekyll build --destination master
          pushd master
          git add --all
          git commit -m "Update _site by GitHub Action" || true
          git push origin master
          popd
