name: Build GitHub Pages

on:
  push:
    branches:
      - develop

jobs:
  build-develop-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Checkout master branch
        uses: actions/checkout@v4
        with:
          ref: master
          path: master
          fetch-depth: 0

      - name: Build Jekyll
        run: |
          sudo apt-get -y --reinstall install imagemagick
          JEKYLL_ENV=production bundle exec jekyll build --destination master

      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Commit and push changes
        run: |
          cd master
          git add --all
          if ! git diff --cached --quiet; then
            git commit -m "Update site content by GitHub Action [skip ci]"
            git push origin master
          else
            echo "No changes to commit"
          fi
          