name: Build GitHub Pages

on:
  push:
    branches:
      - develop

jobs:
  build-develop-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Inject Front Matter into Markdown files
        run: |
          find . -name "*.md" -not -path "*/.*" -not -path "./vendor/*" -not -path "./master/*" | while read -r file; do
            if ! grep -q "^---" "$file"; then
              echo "Injecting Front Matter into: $file"
              {
                echo "---"
                echo "layout: default"
                echo "---"
                echo ""
                cat "$file"
              } > temp_file
              mv temp_file "$file"
            fi
          done

      - name: Checkout master branch
        uses: actions/checkout@v4
        with:
          ref: master
          path: master
          fetch-depth: 0

      - name: Build Jekyll
        run: |
          sudo apt-get -y --reinstall install imagemagick
          JEKYLL_ENV=production bundle exec jekyll build
          rsync -av --delete _site/ master/

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          cd master
          git add --all
          if ! git diff --cached --quiet; then
            git commit -m "Update site content by GitHub Action [skip ci]"
            git push origin master
          else
            echo "No changes to commit"
          fi